#pragma once

enum CursorMode
{
	CMODE_NONE,
	CMODE_LOCKKEYS_NOCURSOR,
	CMODE_LOCKCAMANDCONTROL,
	CMODE_LOCKCAM,
	CMODE_LOCKCAM_NOCURSOR
};

enum GameMode 
{
    GAME_MODE_WAITCONNECT = 0x1,
    GAME_MODE_CONNECTING = 0x2,
    GAME_MODE_CONNECTED = 0x5,
    GAME_MODE_WAITJOIN = 0x6,
    GAME_MODE_RESTARTING = 0xB
};